name: Welcome
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: a_normal_comment
        uses: TejasvOnly/random-rickroll@v1.0
        with:
          percentage: 0.1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
